//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC.ServiceToken {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosRegistroAvaluo", Namespace="http://schemas.datacontract.org/2004/07/TesoreriaDF_WS")]
    [System.SerializableAttribute()]
    public partial class DatosRegistroAvaluo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvaluoXMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Folio_InternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Folio_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvaluoXML {
            get {
                return this.AvaluoXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.AvaluoXMLField, value) != true)) {
                    this.AvaluoXMLField = value;
                    this.RaisePropertyChanged("AvaluoXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folio_Interno {
            get {
                return this.Folio_InternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Folio_InternoField, value) != true)) {
                    this.Folio_InternoField = value;
                    this.RaisePropertyChanged("Folio_Interno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folio_Usuario {
            get {
                return this.Folio_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Folio_UsuarioField, value) != true)) {
                    this.Folio_UsuarioField = value;
                    this.RaisePropertyChanged("Folio_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosAdicionalesAvaluo", Namespace="http://schemas.datacontract.org/2004/07/TesoreriaDF_WS")]
    [System.SerializableAttribute()]
    public partial class DatosAdicionalesAvaluo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_PagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Folio_InternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Folio_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Linea_CapturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Monto_PagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Pago {
            get {
                return this.Fecha_PagoField;
            }
            set {
                if ((this.Fecha_PagoField.Equals(value) != true)) {
                    this.Fecha_PagoField = value;
                    this.RaisePropertyChanged("Fecha_Pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folio_Interno {
            get {
                return this.Folio_InternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Folio_InternoField, value) != true)) {
                    this.Folio_InternoField = value;
                    this.RaisePropertyChanged("Folio_Interno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folio_Usuario {
            get {
                return this.Folio_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Folio_UsuarioField, value) != true)) {
                    this.Folio_UsuarioField = value;
                    this.RaisePropertyChanged("Folio_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Linea_Captura {
            get {
                return this.Linea_CapturaField;
            }
            set {
                if ((object.ReferenceEquals(this.Linea_CapturaField, value) != true)) {
                    this.Linea_CapturaField = value;
                    this.RaisePropertyChanged("Linea_Captura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Monto_Pago {
            get {
                return this.Monto_PagoField;
            }
            set {
                if ((this.Monto_PagoField.Equals(value) != true)) {
                    this.Monto_PagoField = value;
                    this.RaisePropertyChanged("Monto_Pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/TesoreriaDF_WS")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AceptadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aceptado {
            get {
                return this.AceptadoField;
            }
            set {
                if ((this.AceptadoField.Equals(value) != true)) {
                    this.AceptadoField = value;
                    this.RaisePropertyChanged("Aceptado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceToken.IWS_Recibe_Avaluo")]
    public interface IWS_Recibe_Avaluo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Recibe_Avaluo/BandejaAvaluoXML", ReplyAction="http://tempuri.org/IWS_Recibe_Avaluo/BandejaAvaluoXMLResponse")]
        bool BandejaAvaluoXML(LC.ServiceToken.DatosRegistroAvaluo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Recibe_Avaluo/BandejaAvaluoXML", ReplyAction="http://tempuri.org/IWS_Recibe_Avaluo/BandejaAvaluoXMLResponse")]
        System.Threading.Tasks.Task<bool> BandejaAvaluoXMLAsync(LC.ServiceToken.DatosRegistroAvaluo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Recibe_Avaluo/ActualizarEnAvaluoXML", ReplyAction="http://tempuri.org/IWS_Recibe_Avaluo/ActualizarEnAvaluoXMLResponse")]
        LC.ServiceToken.Respuesta ActualizarEnAvaluoXML(LC.ServiceToken.DatosAdicionalesAvaluo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Recibe_Avaluo/ActualizarEnAvaluoXML", ReplyAction="http://tempuri.org/IWS_Recibe_Avaluo/ActualizarEnAvaluoXMLResponse")]
        System.Threading.Tasks.Task<LC.ServiceToken.Respuesta> ActualizarEnAvaluoXMLAsync(LC.ServiceToken.DatosAdicionalesAvaluo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Recibe_Avaluo/obtenertoken", ReplyAction="http://tempuri.org/IWS_Recibe_Avaluo/obtenertokenResponse")]
        void obtenertoken(string folio_avaluo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Recibe_Avaluo/obtenertoken", ReplyAction="http://tempuri.org/IWS_Recibe_Avaluo/obtenertokenResponse")]
        System.Threading.Tasks.Task obtenertokenAsync(string folio_avaluo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWS_Recibe_AvaluoChannel : LC.ServiceToken.IWS_Recibe_Avaluo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_Recibe_AvaluoClient : System.ServiceModel.ClientBase<LC.ServiceToken.IWS_Recibe_Avaluo>, LC.ServiceToken.IWS_Recibe_Avaluo {
        
        public WS_Recibe_AvaluoClient() {
        }
        
        public WS_Recibe_AvaluoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_Recibe_AvaluoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_Recibe_AvaluoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_Recibe_AvaluoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool BandejaAvaluoXML(LC.ServiceToken.DatosRegistroAvaluo datos) {
            return base.Channel.BandejaAvaluoXML(datos);
        }
        
        public System.Threading.Tasks.Task<bool> BandejaAvaluoXMLAsync(LC.ServiceToken.DatosRegistroAvaluo datos) {
            return base.Channel.BandejaAvaluoXMLAsync(datos);
        }
        
        public LC.ServiceToken.Respuesta ActualizarEnAvaluoXML(LC.ServiceToken.DatosAdicionalesAvaluo datos) {
            return base.Channel.ActualizarEnAvaluoXML(datos);
        }
        
        public System.Threading.Tasks.Task<LC.ServiceToken.Respuesta> ActualizarEnAvaluoXMLAsync(LC.ServiceToken.DatosAdicionalesAvaluo datos) {
            return base.Channel.ActualizarEnAvaluoXMLAsync(datos);
        }
        
        public void obtenertoken(string folio_avaluo) {
            base.Channel.obtenertoken(folio_avaluo);
        }
        
        public System.Threading.Tasks.Task obtenertokenAsync(string folio_avaluo) {
            return base.Channel.obtenertokenAsync(folio_avaluo);
        }
    }
}
